typedef long long ll;
typedef pair <int, int> pii;
typedef vector <int> vi;
typedef deque <int> di;
typedef deque <pii> dii;
typedef map <int, di, greater <int> > mii;
typedef set <int> si;
typedef multiset <int> mi;
typedef string st;
typedef priority_queue<pair<int, int>, vector<pair<int, int>>, greater<pair<int, int>>> heap_Dijkstra;